DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `id` INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  `username` VARCHAR(255) DEFAULT NULL COMMENT '用户名',
  `password` VARCHAR(255) DEFAULT NULL COMMENT '密码',
  `birthday` DATETIME DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '用户数据表';